export {default as Sidebar} from './Sidebar'
export {default as Navbar} from './Navbar'
export {default as FormLogin} from './FormLogin'
export {default as Transition} from './Transition'
export {default as UserMenu} from './UserMenu'
export {default as Loader} from './Loader'
export {default as Tap} from './Tap'
export {default as MesasPedidos} from './MesasPedidos'

export {default as TableInicio} from './tables/admin/inicio/TableInicio'
export {default as TableProductos} from './tables/productos/TableProductos'
export {default as TableCuentas} from './tables/admin/cuentas/TableCuentas'
export {default as TableIngredientesTab} from './tables/productos/tab/TableIngredientesTab'
export {default as TableIngredientes} from './tables/admin/ingredientes/TableIngredientes'
export {default as TableOrdenes} from './tables/admin/ordenes/TableOrdenes'
export {default as TableCarritoProductos} from './tables/mesero/realizarPedido/TableCarritoProductos'
export {default as TableProductosMesero} from './tables/mesero/realizarPedido/TableProductosMesero'

export {default as ModalAggCuenta} from './modals/cuentas/ModalAggCuenta'
export {default as ModalEditCuenta} from './modals/cuentas/ModalEditCuenta'
export {default as ModalAggProducto} from './modals/productos/ModalAggProducto'
export {default as ModalAggMesa} from './modals/mesas/ModalAggMesa'
export {default as  ModalAggIngrediente} from './modals/ingredientes/ModalAggIngrediente'
export {default as ModalEditIngrediente} from './modals/ingredientes/ModalEditIngrediente'

export {default as LineChart} from './charts/inicio/LineChart'
export {default as LineCharts} from './charts/inicio/LineCharts'