export {default as Sidebar} from './Sidebar'
export {default as Navbar} from './Navbar'
export {default as FormLogin} from './FormLogin'
export {default as Transition} from './Transition'
export {default as UserMenu} from './UserMenu'
export {default as Loader} from './Loader'
export {default as Tap} from './Tap'

export {default as TableInicio} from './tables/inicio/TableInicio'
export {default as TableProductos} from './tables/productos/TableProductos'
export {default as TableCuentas} from './tables/cuentas/TableCuentas'
export {default as TableIngredientesTab} from './tables/productos/tab/TableIngredientesTab'
export {default as TableIngredientes} from './tables/ingredientes/TableIngredientes'
export {default as TableOrdenes} from './tables/ordenes/TableOrdenes'

export {default as ModalAggCuenta} from './modals/cuentas/ModalAggCuenta'
export {default as ModalAggProducto} from './modals/productos/ModalAggProducto'
export {default as ModalAggMesa} from './modals/mesas/ModalAggMesa'
export {default as  ModalAggIngrediente} from './modals/ingredientes/ModalAggIngrediente'

export {default as LineChart} from './charts/inicio/LineChart'
export {default as LineCharts} from './charts/inicio/LineCharts'